version: "3"
services:
  adservice:
    build: ./adservice
    ports:
     - "9555:9555"
    env_file:
     - .env
  cartservice:
    build: ./cartservice/src
    ports:
     - "7070:7070"
    env_file:
     - .env
  checkoutservice:
    build: ./checkoutservice
    ports:
     - "5050:5050"
    env_file:
     - .env
  currencyservice:
    build: ./currencyservice
    ports:
     - "7000:7000"
    env_file:
     - .env
  emailservice:
    build: ./emailservice
    ports:
     - "5000:8080"
    env_file:
     - .env
  frontend:
    build: ./frontend
    ports:
     - "80:8080"
    env_file:
     - .env
  loadgenerator:
    build: ./loadgenerator
    env_file:
     - .env
  paymentservice:
    build: ./paymentservice
    ports:
     - "50051:50051"
    env_file:
     - .env
  productcatalogservice:
    build: ./productcatalogservice
    ports:
     - "3550:3550"
    env_file:
     - .env
  recommendationservice:
    build: ./recommendationservice
  shippingservice:
    build: ./shippingservice
    ports:
     - "8080:8080"
    env_file:
     - .env
